<?php
//login/login file api
$apiUser_url_address="https://hivaind.ir/DashManage/users.php?usr=";

// index file api 
$api_url_address = "https://hivaind.ir/property/user-check.php?usr=" ;
$apiLabel_url_address = "https://hivaind.ir/DashManage/label.php?id=" ;
$api_last_url_address = "http://hivaind.ir/wil/loglastjson81.php?id=" ;
// $action-login = "https://hivaind.ir/login/login.php"; 

// change password file api 
// $apiUser_url="https://hivaind.ir/DashManage/users.php?usr=".$username;
$apiUpdatePassword_url_address="https://hivaind.ir/DashManage/updatePassword.php?usr=";

// setting file api
//$api_url = "https://hivaind.ir/property/user-check.php?usr=" . strval($username); 
// $apiLabel_url = "https://hivaind.ir/DashManage/label.php?id=" . $clientID; 
// use to all input 
$apiLabelUpdate_url_address="https://hivaind.ir/DashManage/updateLabel.php?id=";

// forgot password file api 
// $apiUser_url = "https://hivaind.ir/DashManage/users.php?usr=" . $username; 
$url_address = 'http://www.hoshiserver.ir/DashManage_new/password/resetPassword.php??';
$apiUpdateForgotPassword_url_address = "https://hivaind.ir/DashManage/updateForgotPassword.php?usr=" ;

//reset password file api
//$apiUser_url = "https://hivaind.ir/DashManage/users.php?usr=" . $_GET["usr"];
$apiResetPassword_url_address = "https://hivaind.ir/DashManage/resetPassword.php?usr=" ;

// monitoring/index file api
//$api_url = "https://hivaind.ir/property/user-check.php?usr=" . strval($username);

//graph/chartapi file api
//$apiLabel_url="https://hivaind.ir/DashManage/label.php?id=";
$api_data_url_address="http://hivaind.ir/wil/arrayjson.php?tname=test81mini&row=20000&id=";
$api_Datetime_url_address = "http://hivaind.ir/wil/arrayjson.php?tname=test81mini&row=20000&in=time_date&id=";

//admindashboard/createId file api
//$apiID_url="https://hivaind.ir/DashManage/label.php?id=";
$apiCreateID_url_address="https://hivaind.ir/DashManage/createIDv6.php?id=";

//admindashboard/createUser file api
//$apiUser_url_newUser="https://hivaind.ir/DashManage/users.php?usr=";
$apiCreateUser_url_address="https://hivaind.ir/DashManage/createUser.php?usr=";
$apiUpdateUser_url_address="https://hivaind.ir/DashManage/updateUser.php?usr=";
//$apiUser_url_newUser="https://hivaind.ir/DashManage/users.php?usr=";
$apiDeleteUser_url_address="https://hivaind.ir/DashManage/deleteUser.php?usr=";
?>








